name: CICD

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
          
      - name: npm lint
        run: |
          npm install
          npm run lint
          
      - name: npm build
        run: |
          npm build
          
      - name: Generate deployment
        run: zip -r deploy.zip . -x '*.git*' 'node_modules*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: test200
          environment_name: Test200-env
          version_label: main-${{github.sha}}
          region: ap-southeast-1
          deployment_package: deploy.zip	
